#! /bin/bash

buildsh="build.sh"
exefile=$buildsh
listmode=0

if [ $# -eq 1 ] ; then
	exefile=$1.sh
fi

if [ "$1" == '-l' ] ; then
	listmode=1
fi

tryrun() {
	if [ -e .$buildsh -o -e $buildsh -o -e ,$buildsh ] ; then
		if [ $listmode -eq 1 ] ; then
			find -maxdepth 1 -type f -name "*\.sh" | sed -e "s%^\./%%" | sed -e 's%\.sh$%%' | sed -e 's%^,%%' | sed -e 's%^\.%%'
			exit
		fi

		for prefix in ',' '' '.' ; do
			if [ -e $prefix$exefile ] ; then
				if [ '#!' == `head --bytes=2 $prefix$exefile` ] ; then
					chmod a+x ./$prefix$exefile >/dev/null 2>&1
					./$prefix$exefile
				else
					sh ./$prefix$exefile
				fi
				exit
			fi
		done
		exit
	fi
}

cd `pwd -P`

while [ "/" != `pwd` ] ; do
	tryrun
	cd ..
done
tryrun

if [ $listmode -eq 1 ] ; then
	exit
fi

echo "not exist \"$exefile\"."
